This is the jupyter notebook for DM&ML Assignment 1 Part B

Q 1.1

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
import matplotlib.pyplot as plt
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import precision_score, recall_score,auc,accuracy_score,classification_report,confusion_matrix

In [2]:
raw_data = pd.read_excel('Forest.xlsx')
print(raw_data.head())

  class  b1  b2  b3   b4  b5   b6   b7  b8  b9  ...  pred_minus_obs_H_b9  \
0    d   39  36  57   91  59  101   93  27  60  ...                -2.36   
1    h   84  30  57  112  51   98   92  26  62  ...                -2.26   
2    s   53  25  49   99  51   93   84  26  58  ...                -1.46   
3    s   59  26  49  103  47   92   82  25  56  ...                 2.68   
4    d   57  49  66  103  64  106  114  28  59  ...                -2.94   

   pred_minus_obs_S_b1  pred_minus_obs_S_b2  pred_minus_obs_S_b3  \
0               -18.41                -1.88                -6.43   
1               -16.27                -1.95                -6.25   
2               -15.92                -1.79                -4.64   
3               -13.77                -2.53                -6.34   
4               -21.74                -1.64                -4.62   

   pred_minus_obs_S_b4  pred_minus_obs_S_b5  pred_minus_obs_S_b6  \
0               -21.03                -1.60                -6.18  

In [3]:
attributes = raw_data.iloc[:,1:].values
labels = raw_data.iloc[:,0].values
pred_train, pred_test, tar_train, tar_test  = train_test_split(attributes,labels,test_size=0.3,random_state=30,stratify=labels)

In [24]:
classifier_DT = DecisionTreeClassifier(criterion="entropy", random_state=999, max_depth=4)
classifier_DT.fit(pred_train,tar_train)
predictions = classifier_DT.predict(pred_test)

In [25]:
print(accuracy_score(tar_test, predictions))
precision = precision_score(y_true=tar_test, y_pred=predictions, average='micro')
print(precision)
recall = recall_score(y_true=tar_test, y_pred=predictions, average='micro')
print(recall)

0.8789808917197452
0.8789808917197452
0.8789808917197452


In [26]:
print(classification_report(tar_test,predictions))

              precision    recall  f1-score   support

          d        0.85      0.92      0.88        48
          h        0.88      0.85      0.86        26
          o        1.00      0.72      0.84        25
          s        0.87      0.93      0.90        58

    accuracy                           0.88       157
   macro avg       0.90      0.85      0.87       157
weighted avg       0.89      0.88      0.88       157



In [27]:
print(confusion_matrix(tar_test,predictions))

[[44  0  0  4]
 [ 0 22  0  4]
 [ 7  0 18  0]
 [ 1  3  0 54]]


In [28]:
MLP_Classifier = MLPClassifier(max_iter=500)
MLP_Classifier.fit(pred_train,np.ravel(tar_train,order='C'))
predictions_MLP = MLP_Classifier.predict(pred_test)

In [29]:
print(classification_report(tar_test,predictions_MLP))

              precision    recall  f1-score   support

          d        0.92      0.96      0.94        48
          h        0.76      0.85      0.80        26
          o        1.00      0.92      0.96        25
          s        0.93      0.88      0.90        58

    accuracy                           0.90       157
   macro avg       0.90      0.90      0.90       157
weighted avg       0.91      0.90      0.91       157



Q 1.2

In [30]:
probDT = classifier_DT.predict_proba(pred_test)
probMLP = MLP_Classifier.predict_proba(pred_test)

In [32]:
probabilities = []
for i in range(len(pred_test)):
#     entry=[]
#     entry.append(probDT[i].tolist())
#     entry.append(probMLP[i].tolist())
    probabilities.append([probDT[i].tolist(),probMLP[i].tolist()])
firstSampleProbability = probabilities[0]
print("\t\t",MLP_Classifier.classes_)
print("Decision Tree\t",firstSampleProbability[0])
print("MLP Classifier\t",firstSampleProbability[1])
# for probability in probabilities:
#     print("Decision Tree\t",probability[0])
#     print("MLP Classifier\t",probability[1])

		 ['d ' 'h ' 'o ' 's ']
Decision Tree	 [0.04032258064516129, 0.008064516129032258, 0.008064516129032258, 0.9435483870967742]
MLP Classifier	 [0.0003590394314074509, 0.004468106916179271, 0.000743252402041874, 0.9944296012503714]


Q 1.3

In [ ]:
There needs to be some average aggregate functions 